from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import io
from datetime import datetime

def generate_pdf_report(target_domain: str, variants: list) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle('Title', parent=styles['Title'],
                                 fontSize=22, textColor=colors.HexColor('#1a1a2e'),
                                 spaceAfter=6, alignment=TA_CENTER)
    subtitle_style = ParagraphStyle('Sub', parent=styles['Normal'],
                                    fontSize=11, textColor=colors.HexColor('#555'),
                                    alignment=TA_CENTER, spaceAfter=20)

    story.append(Paragraph("PhishGuard Security Report", title_style))
    story.append(Paragraph(f"Phishing Domain Analysis for: <b>{target_domain}</b>", subtitle_style))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e24b4a')))
    story.append(Spacer(1, 0.3*inch))

    # Summary
    summary_style = ParagraphStyle('Summary', parent=styles['Normal'],
                                   fontSize=11, leading=18,
                                   backColor=colors.HexColor('#fff3cd'),
                                   borderPadding=(8, 12, 8, 12),
                                   spaceAfter=20)
    story.append(Paragraph(
        f"⚠️  This report contains <b>{len(variants)}</b> potential phishing domain variants "
        f"generated from <b>{target_domain}</b>. These are for security research and defensive "
        f"monitoring purposes only. Register or monitor these domains to protect your brand.",
        summary_style))

    story.append(Spacer(1, 0.2*inch))

    # Table
    header_style = ParagraphStyle('Header', parent=styles['Normal'],
                                  fontSize=10, textColor=colors.white, fontName='Helvetica-Bold')
    cell_style = ParagraphStyle('Cell', parent=styles['Normal'], fontSize=9)

    table_data = [['#', 'Phishing Variant Domain', 'Risk Level', 'Attack Pattern']]

    for i, v in enumerate(variants[:50], 1):
        risk = v.get('risk_level', 'MEDIUM')
        risk_color = colors.HexColor('#e24b4a') if risk == 'HIGH' else (
                     colors.HexColor('#f0994b') if risk == 'MEDIUM' else colors.HexColor('#639922'))
        table_data.append([
            str(i),
            v.get('domain', ''),
            risk,
            v.get('pattern', 'Typosquatting')
        ])

    table = Table(table_data, colWidths=[1*cm, 9*cm, 3*cm, 5*cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a1a2e')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 9),
        ('FONTSIZE', (0,1), (-1,-1), 8),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f8f8f8')]),
        ('GRID', (0,0), (-1,-1), 0.3, colors.HexColor('#ddd')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(table)

    story.append(Spacer(1, 0.3*inch))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'],
                                  fontSize=8, textColor=colors.grey, alignment=TA_CENTER)
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#ddd')))
    story.append(Spacer(1, 0.1*inch))
    story.append(Paragraph(
        "Generated by PhishGuard | For authorized security research only | "
        "Unauthorized use of this data for phishing attacks is illegal.",
        footer_style))

    doc.build(story)
    return buffer.getvalue()
